// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7uuoe9bbT7S186eziwXXs_MQjHGCdKGA',
    appId: '1:630296081271:web:78e3f01fbc0eb61139a772',
    messagingSenderId: '630296081271',
    projectId: 'crudproject-f7f32',
    authDomain: 'crudproject-f7f32.firebaseapp.com',
    storageBucket: 'crudproject-f7f32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xLaXdfQk38n_0AZbdG6O6nSd0UphtGA',
    appId: '1:630296081271:android:659403ca12159bd939a772',
    messagingSenderId: '630296081271',
    projectId: 'crudproject-f7f32',
    storageBucket: 'crudproject-f7f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLVLK8bpqNlnz5qM8Ou2eo6V8eeW_faA',
    appId: '1:630296081271:ios:619224568588bf2c39a772',
    messagingSenderId: '630296081271',
    projectId: 'crudproject-f7f32',
    storageBucket: 'crudproject-f7f32.appspot.com',
    iosClientId: '630296081271-3vsl334vhk79s2of1v56eqnn16tt1sg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLVLK8bpqNlnz5qM8Ou2eo6V8eeW_faA',
    appId: '1:630296081271:ios:619224568588bf2c39a772',
    messagingSenderId: '630296081271',
    projectId: 'crudproject-f7f32',
    storageBucket: 'crudproject-f7f32.appspot.com',
    iosClientId: '630296081271-3vsl334vhk79s2of1v56eqnn16tt1sg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseStore',
  );
}
